#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom
. /tmp/ci/function

SECONDS=0

if [[ $git_cookies != 0 ]]; then

sudo touch /etc/mtab
sudo chmod 777 /etc/mtab

echo "$git_cookies" > ~/git_cookies.sh
bash ~/git_cookies.sh

fi

# Sync source
repo init --depth=1 --no-repo-verify -u https://github.com/xdroid-oss/xd_manifest -b thirteen -g default,-mips,-darwin,-notdefault

# Sync source without unnecessary messages, try with -j30 first, if fails, it will try again
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)

# local manifest
git clone --depth=1 https://github.com/datnerdguy/device_xiaomi_whyred -b xdroid-13 device/xiaomi/whyred
git clone --depth=1 https://github.com/datnerdguy/vendor_xiaomi_whyred -b thirteen-4.19 vendor/xiaomi/whyred
git clone --depth=1 https://github.com/datnerdguy/kernel_xiaomi_whyred -b sapphire kernel/xiaomi/whyred

rm -rf hardware/qcom-caf/msm8998/display
rm -rf hardware/qcom-caf/msm8998/audio
rm -rf hardware/qcom-caf/msm8998/media

git clone --depth=1 https://github.com/datnerdguy/android_hardware_qcom_audio hardware/qcom-caf/msm8998/audio
git clone --depth=1 https://github.com/datnerdguy/android_hardware_qcom_display hardware/qcom-caf/msm8998/display
git clone --depth=1 https://github.com/edwinmoq/android_hardware_qcom_media -b sdm660-4.19 hardware/qcom-caf/msm8998/media

tg "$rom_name source sync completed!
Total Size: $(du -sh /tmp/rom | cut -d - -f 1 | cut -d / -f 1)
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $progress"

echo "$(($SECONDS / 60))" > /tmp/sync_time.txt
